-- SCHEMA DESIGN

CREATE TABLE USERS (
    USER_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(100) NOT NULL,
    DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0
);

CREATE TABLE USER_INFO(
    USER_ID INTEGER,
    USER_PASS VARCHAR(100) NOT NULL
)

CREATE TABLE COMMENTS (
    COMMENT_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID INTEGER NOT NULL,
    PARENT_ID INTEGER DEFAULT 0,
    COMMENT VARCHAR(250),
    DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0
);